const log = console.log;
log([1, 2, 3, 4].filter(x => x % 2).map(x => x * x), [1, [2, [3, [4]]]].flat(2), [[1, 2], [3]].flatMap(x => x));
log([5, 1, 4].toSorted(), [1, 2, 3].toReversed(), [1, 2, 3].with(1, 9), [1, 2, 3].at(-1));
log(Array.from({ length: 3 }, (_, i) => i * 2), Array.of(7, 8), Array.from("héllo"), Array.isArray([]));
const arr = [1, 2, 3, 4, 5]; log(arr.splice(1, 2, "a", "b", "c"), arr);
log([1, 2, 3].indexOf(2), [NaN].includes(NaN), [NaN].indexOf(NaN), [1, 2, 3].find(x => x > 1), [1, 2, 3].findLast(x => x < 3));
log([3, 1, 10, 2].sort(), [3, 1, 10, 2].sort((a, b) => b - a), ["b", "a", "C"].sort());
log([1, 2, 3].join("-"), [null, undefined, 1].join(), [1, [2, [3]]].toString());
log(Object.entries({ a: 1, b: 2 }), Object.fromEntries([["x", 1]]), Object.assign({}, { a: 1 }, { b: 2 }));
const frozen = Object.freeze({ a: 1 }); frozen.a = 2; log(frozen.a, Object.isFrozen(frozen));
log(Object.getOwnPropertyNames("ab"), Object.keys([4, 5]), { a: 1 }.hasOwnProperty("a"));
log("Hello".padStart(8, "*"), "x".repeat(3), " trim ".trim() + "|", "abc".at(-1), "abc".codePointAt(1));
log("a,b,,c".split(","), "a1b2c3".replace(/\d/g, d => d * 2), "aaa".replaceAll("a", "b"), "Hello".startsWith("He"));
log("The Quick fox".match(/[A-Z]/g), "2024-01-05".match(/(\d+)-(\d+)-(\d+)/).slice(1), "test".search(/s/));
log([..."a1b2".matchAll(/\d/g)].map(m => m[0] + m.index), "x".concat("y", 1), "ABC".toLowerCase(), "straße".toUpperCase());
log(/(?<year>\d{4})-(?<month>\d{2})/.exec("on 2024-03").groups.year, "a.b.c".split(".", 2), "camelCaseString".split(/(?=[A-Z])/));
log(Number("0x10"), Number(""), Number("12px"), +"3.5", (255).toString(2), (3.14159).toFixed(3), (1234.5).toLocaleString());
log(Math.max(1, 5, 3), Math.min(), Math.round(2.5), Math.round(-2.5), Math.sign(-3), Math.trunc(-4.7), Math.hypot(3, 4), Math.cbrt(27));
log(Number.isInteger(5.0), Number.isSafeInteger(2 ** 53), Number.EPSILON > 0, (0.000001234).toPrecision(2), (123.456).toExponential(1));
log(JSON.stringify({ a: 1, b: [1, 2], c: { d: "e" } }, null, 2));
log(JSON.stringify([undefined, function () {}, Symbol()]), JSON.stringify({ u: undefined, d: new Date(0) }), JSON.stringify(" \n"));
log(JSON.parse('[1, "2", {"three": 3}]', (k, v) => typeof v === "number" ? v * 10 : v));
const m = new Map(); m.set("a", 1).set({}, 2); log(m.size, m.get("a"), [...m.keys()].length);
const s = new Set([1, 2, 3]); s.delete(2); log([...s], s.has(3));
const wm = new WeakMap(); const key = {}; wm.set(key, "v"); log(wm.get(key), wm.has({}));
const sym = Symbol("desc"); log(sym.toString(), sym.description, Symbol.for("x") === Symbol.for("x"));
log(String(123), String(null), String([1, 2]), String({}), `${[1, 2]}`, 1 + "2", "3" * "4", true + 1, [] + {}, [] == false);
log(parseFloat("3.14abc"), parseInt("08"), isNaN("abc"), encodeURIComponent("a b&c=d/é"), decodeURIComponent("%E2%9C%93"));
log(Reflect.ownKeys({ a: 1, [Symbol("s")]: 2 }).length, Reflect.has({ x: 1 }, "x"), Reflect.getPrototypeOf([]) === Array.prototype);
log(new Date(Date.UTC(2020, 1, 29, 12)).toISOString(), new Date("2020-02-29T12:00:00Z").getTime(), Date.UTC(1970, 0, 1));
log(typeof Date.now(), new Date(2020, 0, 31).getMonth(), new Date("invalid").getTime(), JSON.stringify(new Date(86400000)));
log(Object.prototype.toString.call([]), Object.prototype.toString.call(null), Object.prototype.toString.call(new Map()));
log([1, 2, 3].entries().next(), [..."ab"].entries().toString(), Array.prototype.slice.call({ length: 2, 0: "a", 1: "b" }));
log(Object.getOwnPropertyDescriptor({ get g() { return 1; } }, "g").set, Object.getOwnPropertyDescriptor([1], "length"));
