[workspace]
resolver = "2"
members = ["xtask", "bootloader", "kernel", "libs/bootinfo", "libs/gfx", "libs/elf", "libs/abi", "libs/wavefs", "libs/fat32", "libs/image", "libs/wav", "libs/web", "libs/tls", "libs/surf"]
default-members = ["xtask"]

[workspace.package]
version = "0.5.0"
edition = "2021"
license = "MIT"

[profile.dev]
panic = "abort"
opt-level = 1

[profile.release]
panic = "abort"
opt-level = 3
debug = 1
codegen-units = 1
