//! Native project, package and build operations used by Studio and the CLI.
#![no_std]
extern crate alloc;
use alloc::{
    format,
    string::{String, ToString},
    vec::Vec,
};
use corekit::{fs, process};
pub type Result<T> = core::result::Result<T, String>;
fn io(e: corekit::Error) -> String {
    format!("{e}")
}
pub const TOOLS: &[&str] = &["rustc", "cargo", "rust-lld", "rustfmt", "rust-analyzer"];
pub const TOOLCHAIN: &str = "/System/Developer/bin";
pub fn doctor() -> Vec<String> {
    TOOLS
        .iter()
        .filter(|name| !fs::exists(&format!("{TOOLCHAIN}/{name}")))
        .map(|name| format!("Missing native tool: {name}"))
        .collect()
}
pub fn manifest(project: &str) -> Result<gina::Manifest> {
    let text = fs::read_to_string(&format!("{project}/manifest.toml")).map_err(io)?;
    gina::Manifest::parse(&text).map_err(ToString::to_string)
}
fn mkdirs(path: &str) -> Result<()> {
    let mut p = String::new();
    for part in path.split('/').filter(|s| !s.is_empty()) {
        p.push('/');
        p.push_str(part);
        if !fs::is_dir(&p) {
            fs::mkdir(&p).map_err(io)?;
        }
    }
    Ok(())
}

pub fn new_project(path: &str, id: &str, name: &str) -> Result<()> {
    if fs::exists(path) {
        return Err("That project already exists; choose a new folder.".into());
    }
    if !path.starts_with('/') || !gina::safe_path(path.trim_start_matches('/')) {
        return Err("Choose an absolute project folder without parent traversal.".into());
    }
    let m = gina::Manifest {
        id: id.into(),
        name: name.into(),
        developer: "Independent Developer".into(),
        version: "0.1.0".into(),
        entry: "bin/app".into(),
        icon: String::new(),
        resources: Vec::new(),
        extensions: Vec::new(),
    };
    gina::Manifest::parse(&m.encode()).map_err(ToString::to_string)?;
    mkdirs(&format!("{path}/src"))?;
    mkdirs(&format!("{path}/layouts"))?;
    mkdirs(&format!("{path}/.cargo"))?;
    let files=[("manifest.toml",m.encode()),("Cargo.toml",String::from("[package]\nname = \"gina-app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n[workspace]\n[dependencies]\ncorekit = { path = \"/System/Developer/SDK/userland/corekit\" }\naurorakit = { path = \"/System/Developer/SDK/userland/aurorakit\" }\n[profile.dev]\npanic = \"abort\"\n[profile.release]\npanic = \"abort\"\n")),
        (".cargo/config.toml",String::from("[target.x86_64-aurora-user]\nrustflags = [\"-C\", \"link-arg=--script=/System/Developer/SDK/userland/corekit/user.ld\", \"-C\", \"force-frame-pointers=yes\"]\n")),
        ("layouts/main.ui",String::from("heading Welcome to your app\nlabel Built with AuroraKit\nbutton Continue\n")),
        ("src/main.rs",format!("#![no_std]\n#![no_main]\nextern crate alloc;\nmod generated_ui;\nuse aurorakit::{{App,Env,canvas::Canvas,geom::Rect,ui}};\nstruct Demo {{ ui: ui::State, count:u32 }}\nimpl App for Demo {{\n fn title(&self)->alloc::string::String {{ {:?}.into() }}\n fn size(&self)->(i32,i32) {{ (600,420) }}\n fn draw(&mut self,cv:&mut Canvas,r:Rect,_:&Env) {{ self.ui.draw(cv,&generated_ui::view(),r); }}\n fn click(&mut self,x:i32,y:i32,_:Rect,_:&mut Env)->bool {{ if self.ui.click(x,y).is_some() {{self.count+=1;corekit::println!(\"Action {{}}\",self.count);true}} else {{false}} }}\n fn hover(&mut self,x:i32,y:i32,_:Rect)->bool {{self.ui.hover(x,y)}}\n}}\ncorekit::entry!(main);\nfn main(_:corekit::Args)->i32 {{aurorakit::run(Demo{{ui:ui::State::default(),count:0}})}}\n",name))];
    for (file, bytes) in files {
        fs::write(&format!("{path}/{file}"), bytes.as_bytes()).map_err(io)?;
    }
    generate_ui(path)?;
    fs::sync();
    Ok(())
}

/// Only this generated module is replaced; handwritten code stays untouched.
pub fn generate_ui(project: &str) -> Result<()> {
    let source = fs::read_to_string(&format!("{project}/layouts/main.ui")).map_err(io)?;
    let mut code=String::from("// Generated by Constellation. Edit layouts/main.ui.\nuse aurorakit::ui::View;\npub fn view()->View { View::column(alloc::vec![\n");
    for (i, line) in source.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (kind, text) =
            line.split_once(' ').ok_or_else(|| format!("layouts/main.ui:{}: expected a component and label", i + 1))?;
        let node = match kind {
            "heading" => format!("View::heading({text:?})"),
            "label" => format!("View::label({text:?})"),
            "button" => format!("View::button({}, {text:?})", i + 1),
            "toggle" => format!("View::toggle({}, {text:?},false)", i + 1),
            _ => return Err(format!("layouts/main.ui:{}: unsupported component '{kind}'", i + 1)),
        };
        code.push_str(&node);
        code.push_str(",\n");
    }
    code.push_str("]).padding(24) }\n");
    fs::write(&format!("{project}/src/generated_ui.rs"), code.as_bytes()).map_err(io)
}

pub fn package(project: &str) -> Result<(String, Vec<u8>)> {
    let m = manifest(project)?;
    let executable = fs::read(&format!("{project}/build/app.elf"))
        .map_err(|_| String::from("No compiled app at build/app.elf. Build the project first."))?;
    let mut owned = Vec::new();
    for path in m.resources.iter().chain(core::iter::once(&m.icon)).filter(|s| !s.is_empty()) {
        if !owned.iter().any(|(p, _)| p == path) {
            owned.push((path.clone(), fs::read(&format!("{project}/{path}")).map_err(io)?));
        }
    }
    let mut files = alloc::vec![(m.entry.as_str(), executable.as_slice())];
    files.extend(owned.iter().map(|(p, b)| (p.as_str(), b.as_slice())));
    let bytes = gina::pack(&m, &files).map_err(ToString::to_string)?;
    mkdirs(&format!("{project}/dist"))?;
    let path = format!("{project}/dist/{}-{}.gina", m.id, m.version);
    fs::write(&path, &bytes).map_err(io)?;
    Ok((path, bytes))
}

pub fn build(project: &str, mut log: impl FnMut(&str), cancel: &core::sync::atomic::AtomicBool) -> Result<()> {
    let missing = doctor();
    if !missing.is_empty() {
        return Err(format!(
            "Native Rust toolchain is unavailable on this WaveOS image. {}. No build was performed.",
            missing.join("; ")
        ));
    }
    manifest(project)?;
    generate_ui(project)?;
    let pipe = process::pipe(true).map_err(io)?;
    let cargo = format!("{TOOLCHAIN}/cargo");
    let manifest = format!("{project}/Cargo.toml");
    let out = format!("{project}/build");
    let pid = match process::spawn(
        &cargo,
        &[
            "build",
            "--offline",
            "--config",
            &format!("{project}/.cargo/config.toml"),
            "--manifest-path",
            &manifest,
            "--target",
            "/System/Developer/SDK/userland/x86_64-aurora-user.json",
            "--target-dir",
            &out,
            "-Zjson-target-spec",
        ],
        process::Stdio { stdin: None, stdout: Some(pipe[1]), stderr: Some(pipe[1]) },
    ) {
        Ok(pid) => pid,
        Err(e) => {
            let _ = process::close(pipe[0]);
            let _ = process::close(pipe[1]);
            return Err(io(e));
        }
    };
    let _ = process::close(pipe[1]);
    let mut reader = unsafe { fs::File::from_owned_fd(pipe[0]) };
    let mut buf = [0u8; 2048];
    let code = loop {
        while let Ok(n) = reader.read(&mut buf) {
            if n == 0 {
                break;
            }
            log(&String::from_utf8_lossy(&buf[..n]));
        }
        if cancel.load(core::sync::atomic::Ordering::Relaxed) {
            let _ = process::kill(pid);
            let _ = process::wait(pid, None);
            return Err("Build cancelled.".into());
        }
        if let Ok(code) = process::wait(pid, Some(0)) {
            break code;
        }
        corekit::time::sleep_ms(20);
    };
    if code != 0 {
        return Err(format!("Compiler exited with status {code}. The installed app was preserved."));
    }
    let binary = fs::read(&format!("{out}/x86_64-aurora-user/debug/gina-app")).map_err(io)?;
    fs::write(&format!("{out}/app.elf"), &binary).map_err(io)?;
    Ok(())
}
