[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
gina = { path = "../libs/gina" }
fatfs = "0.3"
aurorafs = { path = "../libs/aurorafs" }
aurora-wav = { path = "../libs/wav" }
webpki-roots = "1"
pulldown-cmark = "0.13"
serde_json = "1"
aurora-help = { path = "../libs/help" }
