[package]
name = "tide"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "tide"
test = false
bench = false

[features]
ktest = []

[dependencies]
bootinfo = { path = "../libs/bootinfo" }
aurora-gfx = { path = "../libs/gfx" }
aurora-abi = { path = "../libs/abi" }
aurora-elf = { path = "../libs/elf" }
wavefs = { path = "../libs/wavefs" }
fat32 = { path = "../libs/fat32" }
x86_64 = "0.15"
spin = "0.9"
linked_list_allocator = "0.10"
