//! aurora-gfx build script.
//!
//! Pre-rasterizes the UI fonts (Inter, JetBrains Mono) into alpha-mask glyph
//! atlases with fontdue on the host, and generates an integer sine table.
//! Consumers embed the result, so neither the kernel nor user programs need a
//! TTF parser or floating-point math at runtime — and text is available even
//! on the kernel's panic screen.

use std::fmt::Write as _;
use std::path::PathBuf;

/// (face id, font file, pixel sizes)
const FACES: &[(&str, &str, &[u32])] = &[
    ("Regular", "Inter-Regular.ttf", &[11, 12, 13, 14, 16, 20]),
    ("SemiBold", "Inter-SemiBold.ttf", &[12, 13, 14, 16, 20, 28, 40]),
    ("Mono", "JetBrainsMono-Regular.ttf", &[13, 14]),
];

const EXTRA_CHARS: &str = "•©…·—–−→←↑↓°×÷±✓⌘⇧éèàüöäñç€£";

fn main() {
    let dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    println!("cargo:rerun-if-changed=build.rs");

    let fonts_dir = PathBuf::from(&dir).join("../../assets/fonts");
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let chars: Vec<char> = (0x20u8..=0x7E).map(char::from).chain(EXTRA_CHARS.chars()).collect();

    let mut src = String::new();
    writeln!(src, "// @generated by kernel/build.rs — do not edit").unwrap();
    writeln!(src, "pub static FACES: &[FaceData] = &[").unwrap();

    for (face, file, sizes) in FACES {
        let path = fonts_dir.join(file);
        println!("cargo:rerun-if-changed={}", path.display());
        let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
        let font = fontdue::Font::from_bytes(bytes, fontdue::FontSettings::default()).unwrap();

        for &size in *sizes {
            let px = size as f32;
            let lm = font.horizontal_line_metrics(px).unwrap();
            let mut blob: Vec<u8> = Vec::new();
            let mut glyphs = String::new();
            for &c in &chars {
                if c != ' ' && font.lookup_glyph_index(c) == 0 {
                    continue; // not in this font
                }
                let (m, bitmap) = font.rasterize(c, px);
                let adv64 = (m.advance_width * 64.0).round() as u32;
                write!(
                    glyphs,
                    "GlyphData{{ch:{},w:{},h:{},xmin:{},ymin:{},adv64:{},off:{}}},",
                    c as u32,
                    m.width,
                    m.height,
                    m.xmin,
                    m.ymin,
                    adv64,
                    blob.len()
                )
                .unwrap();
                blob.extend_from_slice(&bitmap);
            }
            let bin = format!("font-{face}-{size}.bin");
            std::fs::write(out.join(&bin), &blob).unwrap();
            writeln!(
                src,
                "FaceData{{face:Face::{face},size:{size},ascent:{},descent:{},line_height:{},glyphs:&[{glyphs}],bitmap:include_bytes!(concat!(env!(\"OUT_DIR\"),\"/{bin}\"))}},",
                lm.ascent.round() as i32,
                lm.descent.round() as i32,
                lm.new_line_size.round() as i32,
            )
            .unwrap();
        }
    }
    writeln!(src, "];").unwrap();
    std::fs::write(out.join("fonts.rs"), src).unwrap();

    // Integer sine table for the GUI (the kernel is soft-float and has no libm).
    let mut sine = String::from("pub static SINE: [i16; 1024] = [");
    for i in 0..1024 {
        let v = (i as f64 / 1024.0 * std::f64::consts::TAU).sin() * 16384.0;
        write!(sine, "{},", v.round() as i32).unwrap();
    }
    sine.push_str("];\n");
    std::fs::write(out.join("sine.rs"), sine).unwrap();
}
